export enum BridgePaymentScheme {
  SEPA_INSTANT = 'sepa_instant',
  SEPA_CREDIT = 'sepa_credit',
  SEPA_PAYOUT_RETURN = 'sepa_payout_return',
  ADHOC = 'adhoc',
  INT_INTERC = 'int_interc',
  PI_BACS = 'pi_bacs',
  PI_CHAPS = 'pi_chaps',
  PI_DD = 'pi_dd',
  PI_FAST = 'pi_fast',
  PI_MASTER = 'pi_master',
  PI_REV = 'pi_rev',
  PI_VISA = 'pi_visa',
  PO_CHAPS = 'po_chaps',
  PO_DD = 'po_dd',
  PO_FAST = 'po_fast',
  PO_MASTER = 'po_master',
  PO_VISA = 'po_visa',
}
