export enum TablesNames {
  AUDIT = 'audit',
  USERS = 'users',
  VAULT = 'vault',
  VAULTS_CREATOR = 'vaults-creator',
  WALLETS = 'wallet',
  SHAREHOLDERS_CLAIM_ACCOUNTS = 'shareholders-claim-accounts',
  TAX_FORM = 'tax-form',
  SUM_SUB = 'sum-sub',
  TAX_INFORMATION = 'tax-info',
  NOTES = 'notes',
  BANKING_INFO = 'banking-info',
  BRIDGE_KYC = 'bridge-kyc',
  CUSTOMERS = 'customers',
  LIQUIDATION_ADDRESSES = 'liquidation-addresses',
  VIRTUAL_ACCOUNTS = 'virtual-accounts',
  DIRECT_RECIPIENTS = 'direct-recipients',
  PERSONA = 'persona',
  ADDRESS_ACTIVITY = 'address-activity',
  TRANSACTION_ITEMS = 'transaction-items',
}
